### ISSUE TITLE
Web2 Authentication

### ISSUE THREAD

**Issue by tinypell3ts** [open-format/dapp-template#10]
## Feature Description
This feature aims to add Web2 authentication to the DApp template using the magic link service provided by Supabase. The implementation should allow users to register and log in. During registration, a new Ethereum wallet should be created for the user and stored in the database, linked to the user's account. Supabase details must be stored in environment variables for security purposes.

```[tasklist]
### Proposed solution
- [x] Integrate Supabase authentication library and configure it with the project, storing the necessary API keys and configuration in environment variables.
- [x] Create a registration component that allows users to input their email address and request a magic link for authentication.
- [x] Implement an email verification system using Supabase magic links.
- [x] Upon successful email verification, create a new Ethereum wallet for the user.
- [x] Store the newly created Ethereum wallet address in the user's account in the Supabase database.
- [x] Create a login component that allows users to input their email address and request a magic link for authentication.
- [x] Implement a system to log in users using Supabase magic links, granting access to their Ethereum wallets.
- [x] Add functionality to retrieve the user's Ethereum wallet address so that it can be used as the recipient when triggering rewards.
- [x] Implement functionality to ensure that a user can only be authenticated with either Web2 or Web3 at the same time, preventing simultaneous authentication with both methods.
```

## Acceptance Criteria
1. The DApp template should support user registration using Supabase magic links.
2. The DApp template should support user login using Supabase magic links.
3. A new Ethereum wallet should be created for each new user during the registration process.
4. The Ethereum wallet address should be stored in the user's account in the Supabase database.
5. Supabase API keys and configuration should be stored in environment variables for security.
6. The feature should be compatible with the current version of the DApp template.
7. The implementation should provide a function or method to retrieve the user's Ethereum wallet address, enabling its use as the recipient when triggering rewards.
8. The system should ensure that a user can only be authenticated with either Web2 or Web3 at any given time, preventing simultaneous authentication using both methods.

## Alternative Solutions
Instead of using Supabase magic links for authentication, other Web2 authentication providers such as Firebase or Auth0 could be considered. However, Supabase has been chosen due to its easy integration with the DApp template.

## Additional Context
Supabase documentation: https://supabase.io/docs
Example of a magic link authentication with Supabase: https://supabase.io/docs/guides/auth#email-magic-link

## Impact on Existing Codebase
This feature will require changes to the existing authentication system (if any) within the DApp template. It might also require additional dependencies, such as the Supabase authentication library and Ethereum wallet creation libraries.

**Comment by 3rdBlock** [comment]
Authentication for Web2 has been successfully implemented and committed to a separate branch to enable the implementation of distinct templates for developers to utilize.
